name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pytest
        run: poetry run pytest -q

  docker-build:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pipeline:staging .

      # TODO: Add Docker login step if pushing to a private registry
      - name: Docker login (Staging)
        uses: docker/login-action@v3
        with:
          # Replace with your registry URL
          registry: ghcr.io
          # Configure these secrets in your GitHub repository settings
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image (Staging)
        run: docker push ghcr.io/org/pipeline:staging # Replace with actual registry/org

  promote-prod:
    needs: [test, docker-build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # TODO: Add Docker login step if pulling/pushing from/to a private registry
      - name: Docker login (Production)
        uses: docker/login-action@v3
        with:
          # Replace with your registry URL
          registry: ghcr.io
          # Configure these secrets in your GitHub repository settings
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Staging image
        run: docker pull ghcr.io/org/pipeline:staging # Replace with actual registry/org

      - name: Tag Production image
        run: docker tag ghcr.io/org/pipeline:staging ghcr.io/org/pipeline:prod # Replace with actual registry/org

      - name: Push Production image
        run: docker push ghcr.io/org/pipeline:prod # Replace with actual registry/org